/* apps/doom/audio_stubs.c - AUTO-GEN link stubs (C) for the DOOM build (no audio HW).
 * Referenced only by never-executed BT/app-init code (main runs hw_selftest->doom
 * which never returns). Empty stubs just satisfy the linker. C++ ones: audio_stubs_cpp.cpp */
#ifdef DOOM
void a2dp_audio_detect_next_packet_callback_register(void) {}
void a2dp_audio_detect_store_packet_callback_register(void) {}
void a2dp_audio_latency_factor_get(void) {}
void a2dp_audio_latency_factor_set(void) {}
void a2dp_audio_retrigger_is_on_process(void) {}
void a2dp_audio_retrigger_set_on_process(void) {}
void a2dp_audio_store_packet(void) {}
void a2dp_audio_sync_direct_tune_sample_rate(void) {}
void a2dp_audio_sync_init(void) {}
void a2dp_audio_sync_reset_data(void) {}
void a2dp_audio_sync_tune_cancel(void) {}
void a2dp_audio_sync_tune_sample_rate(void) {}
void a2dp_audio_sysfreq_boost_running(void) {}
void a2dp_audio_sysfreq_boost_start(void) {}
void af_close(void) {}
void af_codec_calib_dac_chan_enable(void) {}
void af_codec_calib_dac_dc(void) {}
void af_codec_calib_param_setup(void) {}
void af_open(void) {}
void af_reset_priority(void) {}
void af_set_priority(void) {}
void af_stream_close(void) {}
void af_stream_get_dma_base_addr(void) {}
void af_stream_get_dma_chan(void) {}
void af_stream_open(void) {}
void af_stream_set_chan_vol(void) {}
void af_stream_start(void) {}
void af_stream_stop(void) {}
void app_audio_adm_curr_a2dp_data_need_receive(void) {}
void app_audio_adm_get_bt_active_device(void) {}
void app_audio_adm_get_le_audio_active_device(void) {}
void app_audio_adm_is_any_device_is_streaming(void) {}
void app_audio_adm_music_stream_is_active(void) {}
void app_audio_adm_slave_set_active_device_handler(void) {}
void app_audio_control_call_answer(void) {}
void app_audio_control_call_terminate(void) {}
void app_audio_control_handle_three_way_incoming_call(void) {}
void app_audio_control_media_pause(void) {}
void app_audio_control_media_play(void) {}
void app_audio_control_release_active_call(void) {}
void app_audio_control_streaming_volume_down(void) {}
void app_audio_control_streaming_volume_up(void) {}
void app_audio_manager_ctrl_volume_with_callback(void) {}
void app_audio_manager_open(void) {}
void app_audio_manager_sendrequest(void) {}
void app_audio_manager_sendrequest_need_callback(void) {}
void app_audio_open(void) {}
void app_audio_sendrequest_param(void) {}
void app_audio_toggle_a2dp_cis(void) {}
void app_audio_trigger_toggle_a2dp_cis(void) {}
void app_bt_audio_a2dp_close_req_allow(void) {}
void app_bt_audio_a2dp_disconnect_self_check(void) {}
void app_bt_audio_abandon_focus_timer_handler(void) {}
void app_bt_audio_count_connected_sco(void) {}
void app_bt_audio_count_streaming_a2dp(void) {}
void app_bt_audio_enable_active_link(void) {}
void app_bt_audio_event_handler(void) {}
void app_bt_audio_get_another_hfp_device_for_user_action(void) {}
void app_bt_audio_get_curr_a2dp_device(void) {}
void app_bt_audio_get_curr_hfp_device(void) {}
void app_bt_audio_get_curr_playing_a2dp(void) {}
void app_bt_audio_get_curr_playing_sco(void) {}
void app_bt_audio_get_device_for_user_action(void) {}
void app_bt_audio_get_hfp_device_for_user_action(void) {}
void app_bt_audio_handle_peer_focus_info(void) {}
void app_bt_audio_hfp_get_clcc_timeout_handler(void) {}
void app_bt_audio_init_focus_listener(void) {}
void app_bt_audio_new_sco_is_rejected_by_controller(void) {}
void app_bt_audio_peer_sco_codec_received(void) {}
void app_bt_audio_receive_peer_a2dp_playing_device(void) {}
void app_bt_audio_select_another_call_active_hfp(void) {}
void app_bt_audio_select_another_device_to_create_sco(void) {}
void app_bt_audio_select_another_streaming_a2dp(void) {}
void app_bt_audio_select_bg_a2dp_to_resume(void) {}
void app_bt_audio_select_call_active_hfp(void) {}
void app_bt_audio_self_ring_tone_play_timer_handler(void) {}
void app_bt_audio_strategy_init(void) {}
void app_bt_audio_switch_streaming_a2dp(void) {}
void app_bt_audio_switch_streaming_sco(void) {}
void app_bt_audio_trigger_switch_mute_streaming_sco(void) {}
void app_bt_audio_trigger_switch_streaming_a2dp(void) {}
void app_bt_get_call_state(void) {}
void app_bt_get_music_playback_info(void) {}
void app_bt_get_music_playback_status(void) {}
void app_bt_init_config_postphase(void) {}
void app_bt_stream_trigger_checker_stop(void) {}
void app_bt_stream_trigger_onprocess(void) {}
void app_bt_stream_trigger_stauts_get(void) {}
void app_bt_stream_volume_ptr_update(void) {}
void app_ibrt_custom_play_speed_tuning_req_handler(void) {}
void app_ibrt_send_custom_play_speed_tuning_req(void) {}
void app_ibrt_sync_mix_prompt_req_handler(void) {}
void app_ibrt_sync_target_buf_cnt_req(void) {}
void app_ibrt_sync_target_buf_cnt_req_handler(void) {}
void app_ibrt_sync_target_buf_cnt_rsp_handler(void) {}
void app_ibrt_sync_target_buf_cnt_rsp_timeout_handler(void) {}
void app_play_audio_get_lang(void) {}
void app_play_audio_set_lang(void) {}
void app_prompt_flush_pending_prompts(void) {}
void app_tws_cmd_prompt_play_req_handler(void) {}
void audio_player_dump_playback_status(void) {}
void audio_player_play_prompt(void) {}
void audio_player_playback_stop(void) {}
void audio_player_restore_volume(void) {}
void audio_player_set_volume(void) {}
void audio_player_volume_down(void) {}
void audio_player_volume_up(void) {}
void audio_process_init(void) {}
void audio_process_tws_sync_change(void) {}
void audio_prompt_req_send_failed_cb(void) {}
void bt_a2dp_is_run(void) {}
void bt_is_playback_triggered(void) {}
void bt_media_is_media_active_by_device(void) {}
void media_PlayAudio(void) {}
void media_PlayAudio_standalone(void) {}
void media_PlayAudio_standalone_locally(void) {}
void sbm_control_local_scalable_sbm_feature_handler(void) {}
void sbm_local_scalable_sbm_feature_updated_callback(void) {}
void sco_preempted_time(void) {}
void trigger_media_play(void) {}
void voice_assistant_flag(void) {}
#endif
