/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3 */

#include "current_device_state.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(google_assistant_devices_headphone_v1_CurrentDeviceStatus, google_assistant_devices_headphone_v1_CurrentDeviceStatus, AUTO)


PB_BIND(google_assistant_devices_headphone_v1_BatteryDetails, google_assistant_devices_headphone_v1_BatteryDetails, AUTO)

