/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3 */

#include "device_control_request.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(google_assistant_v1_Execution, google_assistant_v1_Execution, 4)


PB_BIND(google_assistant_v1_Execution_ParamsEntry, google_assistant_v1_Execution_ParamsEntry, 2)
