obj-y += beco_fully_connected_fast.o
obj-y += beco_fully_connected.o
obj-y += beco_depthwise_conv.o
obj-y += beco_convolve_fast.o
obj-y += beco_convolve_1x1_fast.o
obj-y += beco_average_pooling_2x2.o
obj-y += beco_convolve_1xn_fast.o
